version: "3.7"

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8001:8000
    depends_on:
      - database
    environment:
      SECRET_KEY: supersecret
      DATABASE_URL: "postgres://postgres:postgres@database:5432/develop"
      DJANGO_HOSTS: "localhost, 127.0.0.1"
      EMAIL_HOST: "smtp.servermail.io"
      EMAIL_HOST_USER: "username"
      EMAIL_HOST_PASSWORD: "password"
      EMAIL_PORT: 2525

  database:
    image: postgres:11-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "develop"
    healthcheck:
      test: ["CMD", "pg_isready -h localhost"]
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
