# Generated by Django 3.1.7 on 2021-02-23 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_auto_20210223_1614"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookinstance",
            options={
                "ordering": ["due_back"],
                "permissions": (("can_mark_returned", "Set book as returned"),),
                "verbose_name": "bookinstance",
                "verbose_name_plural": "bookinstances",
            },
        ),
    ]
