# Generated by Django 3.1.7 on 2021-03-12 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_auto_20210305_0257"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={
                "ordering": ["id", "title"],
                "verbose_name": "book",
                "verbose_name_plural": "books",
            },
        ),
    ]
