name: check linting and tests

on:
  push:
    branches:
      - "feature/**"
      - "hotfix/**"

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testing
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: set up python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Lint with flake8
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          pre-commit run -a
      - name: Runing tests
        run: |
          pip install -r requirements.txt
          python3 manage.py migrate
          python3 manage.py test --settings=library.settings_test -v 3
      - name: Success message
        run: echo finished working successfully!
