name: compliance job

on:
  push:
    branches:
      - "feature/**"
      - "hotfix/**"

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testing
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: set up python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip -m install pre-commit
          if [ requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Runing pre-commit hooks
        run: |
          pre-commit install
          pre-commit run -a
      - name: Runing tests
        run: |
          python3 manage.py migrate
          python3 manage.py test --settings=base.settings_test -v 2
      - name: Success message
        run: echo finished working successfully!
